# Run through examples in curriculum first

In [1]:
import numpy as np

## Indexing

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a[0]

1

In [5]:
a[:]

array([1, 2, 3])

In [13]:
a[:1] #inclusive when slicing from beginning, but not inclusive when slicing from the end

array([1])

In [14]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [15]:
matrix[1, 1]

5

In [16]:
matrix[1:, :2]

array([[4, 5],
       [7, 8]])

In [17]:
should_include_elements = [True, False, True]
a[should_include_elements]

array([1, 3])

## Vectorized Operations

In [19]:
original_array = [1, 2, 3, 4, 5]
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [20]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n + 1)
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [21]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [22]:
original_array = np.array([1, 2, 3, 4, 5])
original_array + 1

array([2, 3, 4, 5, 6])

In [23]:
my_array = np.array([-3, 0, 3, 16])

print('my_array      == {}'.format(my_array))
print('my_array - 5  == {}'.format(my_array - 5))
print('my_array * 4  == {}'.format(my_array * 4))
print('my_array / 2  == {}'.format(my_array / 2))
print('my_array ** 2 == {}'.format(my_array ** 2))
print('my_array % 2  == {}'.format(my_array % 2))

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


In [24]:
my_array = np.array([-3, 0, 3, 16])

print('my_array       == {}'.format(my_array))
print('my_array == -3 == {}'.format(my_array == -3))
print('my_array >= 0  == {}'.format(my_array >= 0))
print('my_array < 10  == {}'.format(my_array < 10))

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


In [26]:
my_array[my_array > 0]

array([ 3, 16])

In [27]:
my_array[my_array % 2 == 0]

array([ 0, 16])

In [28]:
result = my_array % 2
result == 0

array([False,  True, False,  True])

In [30]:
step_1 = my_array % 2
step_2 = step_1 == 0
step_3 = my_array[step_2]

step_3

array([ 0, 16])

In [31]:
print('1. my_array[my_array % 2 == 0]')
print('    - the original expression')
print('2. my_array[{} % 2 == 0]'.format(my_array))
print('    - variable substitution')
print('3. my_array[{} == 0]'.format(my_array % 2))
print('    - result of performing the vectorized modulus 2')
print('4. my_array[{}]'.format(my_array % 2 == 0))
print('    - result of comparing to 0')
print('5. {}[{}]'.format(my_array, my_array % 2 == 0))
print('    - variable substitution')
print('6. {}'.format(my_array[my_array % 2 == 0]))
print('    - our final result')

1. my_array[my_array % 2 == 0]
    - the original expression
2. my_array[[-3  0  3 16] % 2 == 0]
    - variable substitution
3. my_array[[1 0 1 0] == 0]
    - result of performing the vectorized modulus 2
4. my_array[[False  True False  True]]
    - result of comparing to 0
5. [-3  0  3 16][[False  True False  True]]
    - variable substitution
6. [ 0 16]
    - our final result


## Array Creation

In [32]:
np.random.randn(10)

array([-1.0108973 , -1.9485315 ,  0.62520543, -1.03529426, -0.56172412,
       -0.16903934,  0.30115201, -0.2784296 , -0.68717236, -1.99339745])

In [33]:
np.random.randn(3, 4)

array([[ 3.04572915e-01, -3.34786379e-03,  2.79128252e+00,
         7.78819872e-01],
       [ 1.93299400e-03, -3.93620011e-01, -1.16422060e+00,
         9.08627619e-01],
       [-5.35138575e-01,  3.56853680e-01,  1.80146064e-01,
         1.36486354e+00]])

In [34]:
mu = 100
sigma = 30

sigma * np.random.randn(20) + mu

array([ 62.51223446,  86.43253627,  98.28450584,  34.79767446,
        92.24940134, 112.48112948, 114.96466923, 100.57734681,
       106.05671806,  85.22089861,  76.57267053,  56.86392803,
        90.95289944,  88.28857129, 107.81585508,  97.83049419,
        88.36038285,  82.65338403, 123.56002256, 106.46671838])

In [35]:
print('np.zeros(3)    == {}'.format(np.zeros(3)))
print('np.ones(3)     == {}'.format(np.ones(3)))
print('np.full(3, 17) == {}'.format(np.full(3, 17)))

np.zeros(3)    == [0. 0. 0.]
np.ones(3)     == [1. 1. 1.]
np.full(3, 17) == [17 17 17]


In [36]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.arange(4)

array([0, 1, 2, 3])

In [38]:
np.arange(1, 4)

array([1, 2, 3])

In [39]:
np.arange(1, 4, 2)

array([1, 3])

In [40]:
np.arange(3, 5, 0.5)

array([3. , 3.5, 4. , 4.5])

In [41]:
print('min: 1, max: 4, length = 4 -- {}'.format(np.linspace(1, 4, 4)))
print('min: 1, max: 4, length = 7 -- {} '.format(np.linspace(1, 4, 7)))

min: 1, max: 4, length = 4 -- [1. 2. 3. 4.]
min: 1, max: 4, length = 7 -- [1.  1.5 2.  2.5 3.  3.5 4. ] 


## Array Methods

In [42]:
a = np.array([1, 2, 3, 4, 5])

In [43]:
a.min()

1

In [44]:
a.max()

5

In [45]:
a.mean()

3.0

In [46]:
a.sum()

15

In [47]:
a.std()

1.4142135623730951

# Exercises

In [48]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [49]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

1. How many negative numbers are there?

In [51]:
len(a[a < 0])

4

2. How many positive numbers are there?

In [53]:
len(a[a > 0])

5

3. How many even positive numbers are there?

In [63]:
b = a[a > 0]
b

array([ 4, 10, 12, 23,  3])

In [66]:
c = b[b % 2 == 0]
c

array([ 4, 10, 12])

In [67]:
len(c)

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [78]:
a2 = a + 3
a2

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [79]:
b2 = a2[a2 > 0]
b2

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [82]:
len(b2)

10

5. If you squared each number, what would the new mean and standard deviation be?

In [74]:
squared = a ** 2
squared

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [75]:
squared.mean()

74.0

In [76]:
squared.std()

144.0243035046516

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [84]:
centered = a - a.mean()
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

7. Calculate the z-score for each data point.

In [89]:
z_score = centered / a.std()
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [102]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [103]:
# Use python's built in functionality/operators to determine the following:

In [104]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)
print(sum_of_a)

55


In [105]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a)
print(min_of_a)

1


In [106]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = max(a)
print(max_of_a)

10


In [108]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

mean_of_a = sum(a) / len(a)
print(mean_of_a)

5.5


In [113]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_a = 1
for number in a:
    product_of_a *= number
    
print(product_of_a)

3628800


In [114]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = list()

for number in a:
    squares_of_a.append(number ** 2)
    
print(squares_of_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [115]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = list()

for number in a:
    if number % 2 != 0:
        odds_in_a.append(number)
        
print(odds_in_a)

[1, 3, 5, 7, 9]


In [117]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

evens_in_a = list()

for number in a:
    if number % 2 == 0:
        evens_in_a.append(number)
        
print(evens_in_a)

[2, 4, 6, 8, 10]


In [ ]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

In [128]:
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [129]:
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**
# make b into a numpy array called b_array

b_array = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

print(b)
print(type(b))
print(b_array)
print(type(b_array))

[[3, 4, 5], [6, 7, 8]]
<class 'list'>
[[3 4 5]
 [6 7 8]]
<class 'numpy.ndarray'>


In [137]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable.
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
    
print(sum_of_b)

33


In [138]:
# Using numpy

sum_of_b = b_array.sum()
print(sum_of_b)

33


In [132]:
sum_of_b

33

In [141]:
# Exercise 2 - refactor the following to use numpy. 

min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 

print(min_of_b)

3


In [142]:
# using numpy

min_of_b = b_array.min()
print(min_of_b)

3


In [144]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

print(max_of_b)

8


In [145]:
# using numpy

max_of_b = b_array.max()
print(max_of_b)

8


In [146]:
# Exercise 4 - refactor the following using numpy to find the mean of b

mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

print(mean_of_b)

5.5


In [148]:
# using numpy

mean_of_b = b_array.mean()
print(mean_of_b)

5.5


In [149]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
print(product_of_b)

20160


In [152]:
# using numpy

product_of_b = b_array.prod()
print(product_of_b)

20160


In [154]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 

squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        
print(squares_of_b)

[9, 16, 25, 36, 49, 64]


In [158]:
# using numpy

squares_of_b = np.square(b_array).flatten()
print(squares_of_b)

[ 9 16 25 36 49 64]


In [159]:
# Exercise 7 - refactor using numpy to determine the odds_in_b

odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
print(odds_in_b)

[3, 5, 7]


In [161]:
# using numpy

odds_in_b = b_array[b_array % 2 != 0]
print(odds_in_b)

[3 5 7]


In [162]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers

evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
print(evens_in_b)

[4, 6, 8]


In [163]:
# using numpy

evens_in_b = b_array[b_array % 2 == 0]
print(evens_in_b)

[4 6 8]


In [165]:
# Exercise 9 - print out the shape of the array b.

print(b_array.shape)

(2, 3)


In [167]:
# Exercise 10 - transpose the array b.

print(np.transpose(b_array))

[[3 6]
 [4 7]
 [5 8]]


In [184]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

print(b_array.flatten())
print(b_array.reshape(1 , 6))

[3 4 5 6 7 8]
[[3 4 5 6 7 8]]


In [182]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

print(b_array.reshape(6 , 1))

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [185]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [188]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# make c into a numpy array called c_array

c_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(c)
print(type(c))
print(c_array)
print(type(c_array))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [189]:
# Exercise 1 - Find the min, max, sum, and product of c.

print(c_array.min())
print(c_array.max())
print(c_array.sum())
print(c_array.prod())

1
9
45
362880


In [190]:
# Exercise 2 - Determine the standard deviation of c.

print(c_array.std())

2.581988897471611


In [192]:
# Exercise 3 - Determine the variance of c.

print(c_array.var())

6.666666666666667
6.666666666666667


In [193]:
# Exercise 4 - Print out the shape of the array c

print(c_array.shape)

(3, 3)


In [194]:
# Exercise 5 - Transpose c and print out transposed result.

print(c_array.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [198]:
# Exercise 6 - Get the dot product of the array c with c. 

print(np.dot(c_array, c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [202]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

print((c_array * c_array.transpose()).sum())

261


In [204]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

print((c_array * c_array.transpose()).prod())

131681894400


In [205]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [206]:
# make d into a numpy array called d_array

d_array = np.array(
[
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
)

print(d)
print(type(d))
print(d_array)
print(type(d_array))

[[90, 30, 45, 0, 120, 180], [45, -90, -30, 270, 90, 0], [60, 45, -45, 90, -45, 180]]
<class 'list'>
[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]
<class 'numpy.ndarray'>


In [209]:
# Exercise 1 - Find the sine of all the numbers in d

print(np.sin(d_array))

[[ 0.89399666 -0.98803162  0.85090352  0.          0.58061118 -0.80115264]
 [ 0.85090352 -0.89399666  0.98803162 -0.17604595  0.89399666  0.        ]
 [-0.30481062  0.85090352 -0.85090352  0.89399666 -0.85090352 -0.80115264]]


In [210]:
# Exercise 2 - Find the cosine of all the numbers in d

print(np.cos(d_array))

[[-0.44807362  0.15425145  0.52532199  1.          0.81418097 -0.59846007]
 [ 0.52532199 -0.44807362  0.15425145  0.98438195 -0.44807362  1.        ]
 [-0.95241298  0.52532199  0.52532199 -0.44807362  0.52532199 -0.59846007]]


In [211]:
# Exercise 3 - Find the tangent of all the numbers in d
 
print(np.tan(d_array))

[[-1.99520041 -6.4053312   1.61977519  0.          0.71312301  1.33869021]
 [ 1.61977519  1.99520041  6.4053312  -0.17883906 -1.99520041  0.        ]
 [ 0.32004039  1.61977519 -1.61977519 -1.99520041 -1.61977519  1.33869021]]


In [212]:
# Exercise 4 - Find all the negative numbers in d

print(d_array[d_array < 0])

[-90 -30 -45 -45]


In [213]:
# Exercise 5 - Find all the positive numbers in d

print(d_array[d_array > 0])

[ 90  30  45 120 180  45 270  90  60  45  90 180]


In [214]:
# Exercise 6 - Return an array of only the unique numbers in d.

print(np.unique(d_array))

[-90 -45 -30   0  30  45  60  90 120 180 270]


In [215]:
# Exercise 7 - Determine how many unique numbers there are in d.

print(len(np.unique(d_array)))

11


In [216]:
# Exercise 8 - Print out the shape of d.

print(d_array.shape)

(3, 6)


In [218]:
# Exercise 9 - Transpose and then print out the shape of d.

print(d_array.transpose().shape)

(6, 3)


In [219]:
# Exercise 10 - Reshape d into an array of 9 x 2

print(d_array.reshape(9, 2))

[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
